// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"B-Base","status":true,"description":"","parameters":{}},
{"name":"B-SceneCustomAttributes","status":true,"description":"","parameters":{}},
{"name":"B-CustomAttributes","status":true,"description":"teste","parameters":{}}
];
